version: '3'

services:

  db:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sellers
