spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/sellers?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    url: jdbc:postgresql://db:5432/sellers?useTimezone=true&serverTimezone=UTC
    user: root
    password: admin
  jackson:
    date-format: "yyyy-MM-dd"
