global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-sellers-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080','host.docker.internal:8080']
        labels:
          application: 'api-sellers'